const express = require('express')
const app = express()
const con = require("../../config/db")
app.use(express.json())
const placeController = require('../../controller/placeController')
const bus  = require('../../controller/busController')
app.get('/places',placeController.getPlaces)
app.get('/place/:lat/:lang', placeController.getPlaceId)
app.get('/bus/:lat/:lang',bus.getbusNum)
app.listen(3000,()=>console.log('3000'))